version: '2'

services:
  web:
    env_file:
      - sample-apps/imports-contacts-app/src/.env
    build:
      context: .
      dockerfile: Dockerfile-imports-contacts
    volumes:
      - ./sample-apps/imports-contacts-app/src:/imports-contacts-sample-app/sample-apps/imports-contacts-app/src
      - /imports-contacts-sample-app/sample-apps/imports-contacts-app/src/node_modules
    ports:
      - 3000:3000
    command: npm run dev
