version: "3"
services:
  web:
    environment:
      - USE_SELENIUM_SERVER=true
    env_file:
      - sample-apps/companies-app/src/.env-test
    build:
      context: .
      dockerfile: Dockerfile-companies-test
    volumes:
      - ./sample-apps/companies-app/src:/companies-sample-app/sample-apps/companies-app/src
      - /companies-sample-app/sample-apps/companies-app/src/node_modules
    command: bash ./start-tests.sh
