version: '2'

services:
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - ./sample-apps/limiting-handling-and-retry-app/redis-data:/data
    ports:
      - 6379:6379

  limiting_handling_and_retry_web:
    env_file:
      - sample-apps/limiting-handling-and-retry-app/src/.env
    environment:
      REDIS_HOST: redis
    build:
      context: .
      dockerfile: Dockerfile-limiting-handling-and-retry
    volumes:
      - ./sample-apps/limiting-handling-and-retry-app/src:/limiting-handling-and-retry-sample-app/sample-apps/limiting-handling-and-retry-app/src
      - /limiting-handling-and-retry-sample-app/sample-apps/limiting-handling-and-retry-app/src/node_modules
      - ./sample-apps/limiting-handling-and-retry-app/tools:/limiting-handling-and-retry-sample-app/sample-apps/limiting-handling-and-retry-app/tools
    ports:
      - 3000:3000
    command: ../tools/wait-for-it.sh redis:6379 -t 30 --strict -- npm run dev
    depends_on:
      - redis
