version: "3"
services:
  web:
    environment:
      - USE_SELENIUM_SERVER=true
    env_file:
      - sample-apps/contacts-app/src/.env-test
    build:
      context: .
      dockerfile: Dockerfile-contacts-test
    volumes:
      - ./sample-apps/contacts-app/src:/contacts-sample-app/sample-apps/contacts-app/src
      - /contacts-sample-app/sample-apps/contacts-app/src/node_modules
    command: bash ./start-tests.sh
