version: "3"
services:
  web:
    environment:
      - USE_SELENIUM_SERVER=true
    env_file:
      - src/.env-test
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - ./src:/contacts-sample-app/src
      - /contacts-sample-app/src/node_modules
    command: bash ./start-tests.sh
