version: '2'

services:
  web:
    env_file:
      - src/.env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/companies-sample-app/src
      - /companies-sample-app/src/node_modules
    ports:
      - 3000:3000
    command: npm run dev
